<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Aluno extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Aluno_model');
    } 

    /*
     * Listing of aluno
     */
    function index()
    {
        $data['aluno'] = $this->Aluno_model->get_all_aluno();
        
        $data['_view'] = 'aluno/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new aluno
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'situacao_matricula_id' => $this->input->post('situacao_matricula_id'),
				'semestre_ingresso' => $this->input->post('semestre_ingresso'),
				'sexo' => $this->input->post('sexo'),
				'forma_ingresso_id' => $this->input->post('forma_ingresso_id'),
				'tipo_cota_id' => $this->input->post('tipo_cota_id'),
				'cor_raca_id' => $this->input->post('cor_raca_id'),
				'faixa_renda_familiar_id' => $this->input->post('faixa_renda_familiar_id'),
				'faixa_renda_pc_id' => $this->input->post('faixa_renda_pc_id'),
				'escola_origem_id' => $this->input->post('escola_origem_id'),
				'matriz_curricular_id' => $this->input->post('matriz_curricular_id'),
				'cidade_id' => $this->input->post('cidade_id'),
				'ano_ingresso' => $this->input->post('ano_ingresso'),
				'ano_nascimento' => $this->input->post('ano_nascimento'),
				'distancia_km' => $this->input->post('distancia_km'),
				'horas_desloc' => $this->input->post('horas_desloc'),
				'min_desloc' => $this->input->post('min_desloc'),
				'percentual_frequencia' => $this->input->post('percentual_frequencia'),
				'ch_obr_exigida' => $this->input->post('ch_obr_exigida'),
				'ch_obr_cumprida' => $this->input->post('ch_obr_cumprida'),
				'ch_opt_exigida' => $this->input->post('ch_opt_exigida'),
				'ch_opt_cumprida' => $this->input->post('ch_opt_cumprida'),
				'ch_est_exigida' => $this->input->post('ch_est_exigida'),
				'ch_est_cumprida' => $this->input->post('ch_est_cumprida'),
				'ch_com_exigida' => $this->input->post('ch_com_exigida'),
				'ch_com_cumprida' => $this->input->post('ch_com_cumprida'),
				'ch_ele_exigida' => $this->input->post('ch_ele_exigida'),
				'ch_ele_cumprida' => $this->input->post('ch_ele_cumprida'),
				'ch_tcc_exigida' => $this->input->post('ch_tcc_exigida'),
				'ch_tcc_cumprida' => $this->input->post('ch_tcc_cumprida'),
				'ch_tot_exigida' => $this->input->post('ch_tot_exigida'),
				'ch_tot_cumprida' => $this->input->post('ch_tot_cumprida'),
				'cr_tot_exigida' => $this->input->post('cr_tot_exigida'),
				'cr_tot_cumprida' => $this->input->post('cr_tot_cumprida'),
				'hash' => $this->input->post('hash'),
            );
            
            $aluno_id = $this->Aluno_model->add_aluno($params);
            redirect('aluno/index');
        }
        else
        {            
            $data['_view'] = 'aluno/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a aluno
     */
    function edit($id)
    {   
        // check if the aluno exists before trying to edit it
        $data['aluno'] = $this->Aluno_model->get_aluno($id);
        
        if(isset($data['aluno']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'situacao_matricula_id' => $this->input->post('situacao_matricula_id'),
					'semestre_ingresso' => $this->input->post('semestre_ingresso'),
					'sexo' => $this->input->post('sexo'),
					'forma_ingresso_id' => $this->input->post('forma_ingresso_id'),
					'tipo_cota_id' => $this->input->post('tipo_cota_id'),
					'cor_raca_id' => $this->input->post('cor_raca_id'),
					'faixa_renda_familiar_id' => $this->input->post('faixa_renda_familiar_id'),
					'faixa_renda_pc_id' => $this->input->post('faixa_renda_pc_id'),
					'escola_origem_id' => $this->input->post('escola_origem_id'),
					'matriz_curricular_id' => $this->input->post('matriz_curricular_id'),
					'cidade_id' => $this->input->post('cidade_id'),
					'ano_ingresso' => $this->input->post('ano_ingresso'),
					'ano_nascimento' => $this->input->post('ano_nascimento'),
					'distancia_km' => $this->input->post('distancia_km'),
					'horas_desloc' => $this->input->post('horas_desloc'),
					'min_desloc' => $this->input->post('min_desloc'),
					'percentual_frequencia' => $this->input->post('percentual_frequencia'),
					'ch_obr_exigida' => $this->input->post('ch_obr_exigida'),
					'ch_obr_cumprida' => $this->input->post('ch_obr_cumprida'),
					'ch_opt_exigida' => $this->input->post('ch_opt_exigida'),
					'ch_opt_cumprida' => $this->input->post('ch_opt_cumprida'),
					'ch_est_exigida' => $this->input->post('ch_est_exigida'),
					'ch_est_cumprida' => $this->input->post('ch_est_cumprida'),
					'ch_com_exigida' => $this->input->post('ch_com_exigida'),
					'ch_com_cumprida' => $this->input->post('ch_com_cumprida'),
					'ch_ele_exigida' => $this->input->post('ch_ele_exigida'),
					'ch_ele_cumprida' => $this->input->post('ch_ele_cumprida'),
					'ch_tcc_exigida' => $this->input->post('ch_tcc_exigida'),
					'ch_tcc_cumprida' => $this->input->post('ch_tcc_cumprida'),
					'ch_tot_exigida' => $this->input->post('ch_tot_exigida'),
					'ch_tot_cumprida' => $this->input->post('ch_tot_cumprida'),
					'cr_tot_exigida' => $this->input->post('cr_tot_exigida'),
					'cr_tot_cumprida' => $this->input->post('cr_tot_cumprida'),
					'hash' => $this->input->post('hash'),
                );

                $this->Aluno_model->update_aluno($id,$params);            
                redirect('aluno/index');
            }
            else
            {
                $data['_view'] = 'aluno/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The aluno you are trying to edit does not exist.');
    } 

    /*
     * Deleting aluno
     */
    function remove($id)
    {
        $aluno = $this->Aluno_model->get_aluno($id);

        // check if the aluno exists before trying to delete it
        if(isset($aluno['id']))
        {
            $this->Aluno_model->delete_aluno($id);
            redirect('aluno/index');
        }
        else
            show_error('The aluno you are trying to delete does not exist.');
    }
    
}
