<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Area_conhecimento extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Area_conhecimento_model');
    } 

    /*
     * Listing of area_conhecimento
     */
    function index()
    {
        $data['area_conhecimento'] = $this->Area_conhecimento_model->get_all_area_conhecimento();
        
        $data['_view'] = 'area_conhecimento/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new area_conhecimento
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nome' => $this->input->post('nome'),
            );
            
            $area_conhecimento_id = $this->Area_conhecimento_model->add_area_conhecimento($params);
            redirect('area_conhecimento/index');
        }
        else
        {            
            $data['_view'] = 'area_conhecimento/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a area_conhecimento
     */
    function edit($id)
    {   
        // check if the area_conhecimento exists before trying to edit it
        $data['area_conhecimento'] = $this->Area_conhecimento_model->get_area_conhecimento($id);
        
        if(isset($data['area_conhecimento']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nome' => $this->input->post('nome'),
                );

                $this->Area_conhecimento_model->update_area_conhecimento($id,$params);            
                redirect('area_conhecimento/index');
            }
            else
            {
                $data['_view'] = 'area_conhecimento/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The area_conhecimento you are trying to edit does not exist.');
    } 

    /*
     * Deleting area_conhecimento
     */
    function remove($id)
    {
        $area_conhecimento = $this->Area_conhecimento_model->get_area_conhecimento($id);

        // check if the area_conhecimento exists before trying to delete it
        if(isset($area_conhecimento['id']))
        {
            $this->Area_conhecimento_model->delete_area_conhecimento($id);
            redirect('area_conhecimento/index');
        }
        else
            show_error('The area_conhecimento you are trying to delete does not exist.');
    }
    
}
