<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Atividade_extraclasse_has_docente extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Atividade_extraclasse_has_docente_model');
    } 

    /*
     * Listing of atividade_extraclasse_has_docente
     */
    function index()
    {
        $data['atividade_extraclasse_has_docente'] = $this->Atividade_extraclasse_has_docente_model->get_all_atividade_extraclasse_has_docente();
        
        $data['_view'] = 'atividade_extraclasse_has_docente/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new atividade_extraclasse_has_docente
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'atividade_extraclasse_id' => $this->input->post('atividade_extraclasse_id'),
				'docente_id' => $this->input->post('docente_id'),
            );
            
            $atividade_extraclasse_has_docente_id = $this->Atividade_extraclasse_has_docente_model->add_atividade_extraclasse_has_docente($params);
            redirect('atividade_extraclasse_has_docente/index');
        }
        else
        {            
            $data['_view'] = 'atividade_extraclasse_has_docente/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a atividade_extraclasse_has_docente
     */
    function edit($id)
    {   
        // check if the atividade_extraclasse_has_docente exists before trying to edit it
        $data['atividade_extraclasse_has_docente'] = $this->Atividade_extraclasse_has_docente_model->get_atividade_extraclasse_has_docente($id);
        
        if(isset($data['atividade_extraclasse_has_docente']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'atividade_extraclasse_id' => $this->input->post('atividade_extraclasse_id'),
					'docente_id' => $this->input->post('docente_id'),
                );

                $this->Atividade_extraclasse_has_docente_model->update_atividade_extraclasse_has_docente($id,$params);            
                redirect('atividade_extraclasse_has_docente/index');
            }
            else
            {
                $data['_view'] = 'atividade_extraclasse_has_docente/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The atividade_extraclasse_has_docente you are trying to edit does not exist.');
    } 

    /*
     * Deleting atividade_extraclasse_has_docente
     */
    function remove($id)
    {
        $atividade_extraclasse_has_docente = $this->Atividade_extraclasse_has_docente_model->get_atividade_extraclasse_has_docente($id);

        // check if the atividade_extraclasse_has_docente exists before trying to delete it
        if(isset($atividade_extraclasse_has_docente['id']))
        {
            $this->Atividade_extraclasse_has_docente_model->delete_atividade_extraclasse_has_docente($id);
            redirect('atividade_extraclasse_has_docente/index');
        }
        else
            show_error('The atividade_extraclasse_has_docente you are trying to delete does not exist.');
    }
    
}
