<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Atividade_extraclasse extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Atividade_extraclasse_model');
    } 

    /*
     * Listing of atividade_extraclasse
     */
    function index()
    {
        $data['atividade_extraclasse'] = $this->Atividade_extraclasse_model->get_all_atividade_extraclasse();
        
        $data['_view'] = 'atividade_extraclasse/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new atividade_extraclasse
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'remuneracao' => $this->input->post('remuneracao'),
				'titulo' => $this->input->post('titulo'),
				'duracao' => $this->input->post('duracao'),
				'area_conhecimento_id' => $this->input->post('area_conhecimento_id'),
				'tipo_atividade_id' => $this->input->post('tipo_atividade_id'),
            );
            
            $atividade_extraclasse_id = $this->Atividade_extraclasse_model->add_atividade_extraclasse($params);
            redirect('atividade_extraclasse/index');
        }
        else
        {            
            $data['_view'] = 'atividade_extraclasse/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a atividade_extraclasse
     */
    function edit($id)
    {   
        // check if the atividade_extraclasse exists before trying to edit it
        $data['atividade_extraclasse'] = $this->Atividade_extraclasse_model->get_atividade_extraclasse($id);
        
        if(isset($data['atividade_extraclasse']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'remuneracao' => $this->input->post('remuneracao'),
					'titulo' => $this->input->post('titulo'),
					'duracao' => $this->input->post('duracao'),
					'area_conhecimento_id' => $this->input->post('area_conhecimento_id'),
					'tipo_atividade_id' => $this->input->post('tipo_atividade_id'),
                );

                $this->Atividade_extraclasse_model->update_atividade_extraclasse($id,$params);            
                redirect('atividade_extraclasse/index');
            }
            else
            {
                $data['_view'] = 'atividade_extraclasse/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The atividade_extraclasse you are trying to edit does not exist.');
    } 

    /*
     * Deleting atividade_extraclasse
     */
    function remove($id)
    {
        $atividade_extraclasse = $this->Atividade_extraclasse_model->get_atividade_extraclasse($id);

        // check if the atividade_extraclasse exists before trying to delete it
        if(isset($atividade_extraclasse['id']))
        {
            $this->Atividade_extraclasse_model->delete_atividade_extraclasse($id);
            redirect('atividade_extraclasse/index');
        }
        else
            show_error('The atividade_extraclasse you are trying to delete does not exist.');
    }
    
}
