<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cidade extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cidade_model');
    } 

    /*
     * Listing of cidade
     */
    function index()
    {
        $data['cidade'] = $this->Cidade_model->get_all_cidade();
        
        $data['_view'] = 'cidade/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new cidade
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'descricao' => $this->input->post('descricao'),
            );
            
            $cidade_id = $this->Cidade_model->add_cidade($params);
            redirect('cidade/index');
        }
        else
        {            
            $data['_view'] = 'cidade/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a cidade
     */
    function edit($id)
    {   
        // check if the cidade exists before trying to edit it
        $data['cidade'] = $this->Cidade_model->get_cidade($id);
        
        if(isset($data['cidade']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'descricao' => $this->input->post('descricao'),
                );

                $this->Cidade_model->update_cidade($id,$params);            
                redirect('cidade/index');
            }
            else
            {
                $data['_view'] = 'cidade/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The cidade you are trying to edit does not exist.');
    } 

    /*
     * Deleting cidade
     */
    function remove($id)
    {
        $cidade = $this->Cidade_model->get_cidade($id);

        // check if the cidade exists before trying to delete it
        if(isset($cidade['id']))
        {
            $this->Cidade_model->delete_cidade($id);
            redirect('cidade/index');
        }
        else
            show_error('The cidade you are trying to delete does not exist.');
    }
    
}
