<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Disciplina extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Disciplina_model');
    } 

    /*
     * Listing of disciplina
     */
    function index()
    {
        $data['disciplina'] = $this->Disciplina_model->get_all_disciplina();
        
        $data['_view'] = '/sape/disciplina/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new disciplina
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nome' => $this->input->post('nome'),
				'ch' => $this->input->post('ch'),
				'codigo' => $this->input->post('codigo'),
				'tipo' => $this->input->post('tipo'),
            );
            
            $disciplina_id = $this->Disciplina_model->add_disciplina($params);
            redirect('/sape/disciplina/index');
        }
        else
        {            
            $data['_view'] = '/sape/disciplina/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a disciplina
     */
    function edit($id)
    {   
        // check if the disciplina exists before trying to edit it
        $data['disciplina'] = $this->Disciplina_model->get_disciplina($id);
        
        if(isset($data['disciplina']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nome' => $this->input->post('nome'),
					'ch' => $this->input->post('ch'),
					'codigo' => $this->input->post('codigo'),
					'tipo' => $this->input->post('tipo'),
                );

                $this->Disciplina_model->update_disciplina($id,$params);            
                redirect('/sape/disciplina/index');
            }
            else
            {
                $data['_view'] = '/sape/disciplina/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The disciplina you are trying to edit does not exist.');
    } 

    /*
     * Deleting disciplina
     */
    function remove($id)
    {
        $disciplina = $this->Disciplina_model->get_disciplina($id);

        // check if the disciplina exists before trying to delete it
        if(isset($disciplina['id']))
        {
            $this->Disciplina_model->delete_disciplina($id);
            redirect('/sape/disciplina/index');
        }
        else
            show_error('The disciplina you are trying to delete does not exist.');
    }
    
}
