<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Docente_has_disciplina extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Docente_has_disciplina_model');
    } 

    /*
     * Listing of docente_has_disciplina
     */
    function index()
    {
        $data['docente_has_disciplina'] = $this->Docente_has_disciplina_model->get_all_docente_has_disciplina();
        
        $data['_view'] = 'docente_has_disciplina/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new docente_has_disciplina
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'docente_id' => $this->input->post('docente_id'),
				'disciplina_id' => $this->input->post('disciplina_id'),
				'codigo' => $this->input->post('codigo'),
				'ano' => $this->input->post('ano'),
				'periodo' => $this->input->post('periodo'),
				'vagas' => $this->input->post('vagas'),
				'alunos' => $this->input->post('alunos'),
				'docente_codigo' => $this->input->post('docente_codigo'),
            );
            
            $docente_has_disciplina_id = $this->Docente_has_disciplina_model->add_docente_has_disciplina($params);
            redirect('docente_has_disciplina/index');
        }
        else
        {            
            $data['_view'] = 'docente_has_disciplina/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a docente_has_disciplina
     */
    function edit($id)
    {   
        // check if the docente_has_disciplina exists before trying to edit it
        $data['docente_has_disciplina'] = $this->Docente_has_disciplina_model->get_docente_has_disciplina($id);
        
        if(isset($data['docente_has_disciplina']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'docente_id' => $this->input->post('docente_id'),
					'disciplina_id' => $this->input->post('disciplina_id'),
					'codigo' => $this->input->post('codigo'),
					'ano' => $this->input->post('ano'),
					'periodo' => $this->input->post('periodo'),
					'vagas' => $this->input->post('vagas'),
					'alunos' => $this->input->post('alunos'),
					'docente_codigo' => $this->input->post('docente_codigo'),
                );

                $this->Docente_has_disciplina_model->update_docente_has_disciplina($id,$params);            
                redirect('docente_has_disciplina/index');
            }
            else
            {
                $data['_view'] = 'docente_has_disciplina/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The docente_has_disciplina you are trying to edit does not exist.');
    } 

    /*
     * Deleting docente_has_disciplina
     */
    function remove($id)
    {
        $docente_has_disciplina = $this->Docente_has_disciplina_model->get_docente_has_disciplina($id);

        // check if the docente_has_disciplina exists before trying to delete it
        if(isset($docente_has_disciplina['id']))
        {
            $this->Docente_has_disciplina_model->delete_docente_has_disciplina($id);
            redirect('docente_has_disciplina/index');
        }
        else
            show_error('The docente_has_disciplina you are trying to delete does not exist.');
    }
    
}
