<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Docente extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Docente_model');
    } 

    /*
     * Listing of docente
     */
    function index()
    {
        $data['docente'] = $this->Docente_model->get_all_docente();
        
        $data['_view'] = 'docente/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new docente
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'efetivo' => $this->input->post('efetivo'),
				'codigo' => $this->input->post('codigo'),
            );
            
            $docente_id = $this->Docente_model->add_docente($params);
            redirect('docente/index');
        }
        else
        {            
            $data['_view'] = 'docente/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a docente
     */
    function edit($id)
    {   
        // check if the docente exists before trying to edit it
        $data['docente'] = $this->Docente_model->get_docente($id);
        
        if(isset($data['docente']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'efetivo' => $this->input->post('efetivo'),
					'codigo' => $this->input->post('codigo'),
                );

                $this->Docente_model->update_docente($id,$params);            
                redirect('docente/index');
            }
            else
            {
                $data['_view'] = 'docente/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The docente you are trying to edit does not exist.');
    } 

    /*
     * Deleting docente
     */
    function remove($id)
    {
        $docente = $this->Docente_model->get_docente($id);

        // check if the docente exists before trying to delete it
        if(isset($docente['id']))
        {
            $this->Docente_model->delete_docente($id);
            redirect('docente/index');
        }
        else
            show_error('The docente you are trying to delete does not exist.');
    }
    
}
