<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Escola_origem extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Escola_origem_model');
    } 

    /*
     * Listing of escola_origem
     */
    function index()
    {
        $data['escola_origem'] = $this->Escola_origem_model->get_all_escola_origem();
        
        $data['_view'] = 'escola_origem/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new escola_origem
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'descricao' => $this->input->post('descricao'),
            );
            
            $escola_origem_id = $this->Escola_origem_model->add_escola_origem($params);
            redirect('escola_origem/index');
        }
        else
        {            
            $data['_view'] = 'escola_origem/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a escola_origem
     */
    function edit($id)
    {   
        // check if the escola_origem exists before trying to edit it
        $data['escola_origem'] = $this->Escola_origem_model->get_escola_origem($id);
        
        if(isset($data['escola_origem']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'descricao' => $this->input->post('descricao'),
                );

                $this->Escola_origem_model->update_escola_origem($id,$params);            
                redirect('escola_origem/index');
            }
            else
            {
                $data['_view'] = 'escola_origem/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The escola_origem you are trying to edit does not exist.');
    } 

    /*
     * Deleting escola_origem
     */
    function remove($id)
    {
        $escola_origem = $this->Escola_origem_model->get_escola_origem($id);

        // check if the escola_origem exists before trying to delete it
        if(isset($escola_origem['id']))
        {
            $this->Escola_origem_model->delete_escola_origem($id);
            redirect('escola_origem/index');
        }
        else
            show_error('The escola_origem you are trying to delete does not exist.');
    }
    
}
