<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Faixa_renda_pc extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Faixa_renda_pc_model');
    } 

    /*
     * Listing of faixa_renda_pc
     */
    function index()
    {
        $data['faixa_renda_pc'] = $this->Faixa_renda_pc_model->get_all_faixa_renda_pc();
        
        $data['_view'] = 'faixa_renda_pc/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new faixa_renda_pc
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'descricao' => $this->input->post('descricao'),
            );
            
            $faixa_renda_pc_id = $this->Faixa_renda_pc_model->add_faixa_renda_pc($params);
            redirect('faixa_renda_pc/index');
        }
        else
        {            
            $data['_view'] = 'faixa_renda_pc/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a faixa_renda_pc
     */
    function edit($id)
    {   
        // check if the faixa_renda_pc exists before trying to edit it
        $data['faixa_renda_pc'] = $this->Faixa_renda_pc_model->get_faixa_renda_pc($id);
        
        if(isset($data['faixa_renda_pc']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'descricao' => $this->input->post('descricao'),
                );

                $this->Faixa_renda_pc_model->update_faixa_renda_pc($id,$params);            
                redirect('faixa_renda_pc/index');
            }
            else
            {
                $data['_view'] = 'faixa_renda_pc/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The faixa_renda_pc you are trying to edit does not exist.');
    } 

    /*
     * Deleting faixa_renda_pc
     */
    function remove($id)
    {
        $faixa_renda_pc = $this->Faixa_renda_pc_model->get_faixa_renda_pc($id);

        // check if the faixa_renda_pc exists before trying to delete it
        if(isset($faixa_renda_pc['id']))
        {
            $this->Faixa_renda_pc_model->delete_faixa_renda_pc($id);
            redirect('faixa_renda_pc/index');
        }
        else
            show_error('The faixa_renda_pc you are trying to delete does not exist.');
    }
    
}
