<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Situacao_matricula extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Situacao_matricula_model');
    } 

    /*
     * Listing of situacao_matricula
     */
    function index()
    {
        $data['situacao_matricula'] = $this->Situacao_matricula_model->get_all_situacao_matricula();
        
        $data['_view'] = 'situacao_matricula/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new situacao_matricula
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'descricao' => $this->input->post('descricao'),
            );
            
            $situacao_matricula_id = $this->Situacao_matricula_model->add_situacao_matricula($params);
            redirect('situacao_matricula/index');
        }
        else
        {            
            $data['_view'] = 'situacao_matricula/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a situacao_matricula
     */
    function edit($id)
    {   
        // check if the situacao_matricula exists before trying to edit it
        $data['situacao_matricula'] = $this->Situacao_matricula_model->get_situacao_matricula($id);
        
        if(isset($data['situacao_matricula']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'descricao' => $this->input->post('descricao'),
                );

                $this->Situacao_matricula_model->update_situacao_matricula($id,$params);            
                redirect('situacao_matricula/index');
            }
            else
            {
                $data['_view'] = 'situacao_matricula/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The situacao_matricula you are trying to edit does not exist.');
    } 

    /*
     * Deleting situacao_matricula
     */
    function remove($id)
    {
        $situacao_matricula = $this->Situacao_matricula_model->get_situacao_matricula($id);

        // check if the situacao_matricula exists before trying to delete it
        if(isset($situacao_matricula['id']))
        {
            $this->Situacao_matricula_model->delete_situacao_matricula($id);
            redirect('situacao_matricula/index');
        }
        else
            show_error('The situacao_matricula you are trying to delete does not exist.');
    }
    
}
