<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_atividade extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipo_atividade_model');
    } 

    /*
     * Listing of tipo_atividade
     */
    function index()
    {
        $data['tipo_atividade'] = $this->Tipo_atividade_model->get_all_tipo_atividade();
        
        $data['_view'] = 'tipo_atividade/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tipo_atividade
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nome' => $this->input->post('nome'),
				'setor_responsavel' => $this->input->post('setor_responsavel'),
				'descricao' => $this->input->post('descricao'),
            );
            
            $tipo_atividade_id = $this->Tipo_atividade_model->add_tipo_atividade($params);
            redirect('tipo_atividade/index');
        }
        else
        {            
            $data['_view'] = 'tipo_atividade/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tipo_atividade
     */
    function edit($id)
    {   
        // check if the tipo_atividade exists before trying to edit it
        $data['tipo_atividade'] = $this->Tipo_atividade_model->get_tipo_atividade($id);
        
        if(isset($data['tipo_atividade']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nome' => $this->input->post('nome'),
					'setor_responsavel' => $this->input->post('setor_responsavel'),
					'descricao' => $this->input->post('descricao'),
                );

                $this->Tipo_atividade_model->update_tipo_atividade($id,$params);            
                redirect('tipo_atividade/index');
            }
            else
            {
                $data['_view'] = 'tipo_atividade/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tipo_atividade you are trying to edit does not exist.');
    } 

    /*
     * Deleting tipo_atividade
     */
    function remove($id)
    {
        $tipo_atividade = $this->Tipo_atividade_model->get_tipo_atividade($id);

        // check if the tipo_atividade exists before trying to delete it
        if(isset($tipo_atividade['id']))
        {
            $this->Tipo_atividade_model->delete_tipo_atividade($id);
            redirect('tipo_atividade/index');
        }
        else
            show_error('The tipo_atividade you are trying to delete does not exist.');
    }
    
}
