<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Aluno_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get aluno by id
     */
    function get_aluno($id)
    {
        return $this->db->get_where('aluno',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all aluno
     */
    function get_all_aluno()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('aluno')->result_array();
    }
        
    /*
     * function to add new aluno
     */
    function add_aluno($params)
    {
        $this->db->insert('aluno',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update aluno
     */
    function update_aluno($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('aluno',$params);
    }
    
    /*
     * function to delete aluno
     */
    function delete_aluno($id)
    {
        return $this->db->delete('aluno',array('id'=>$id));
    }
}
