<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Area_conhecimento_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get area_conhecimento by id
     */
    function get_area_conhecimento($id)
    {
        return $this->db->get_where('area_conhecimento',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all area_conhecimento
     */
    function get_all_area_conhecimento()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('area_conhecimento')->result_array();
    }
        
    /*
     * function to add new area_conhecimento
     */
    function add_area_conhecimento($params)
    {
        $this->db->insert('area_conhecimento',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update area_conhecimento
     */
    function update_area_conhecimento($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('area_conhecimento',$params);
    }
    
    /*
     * function to delete area_conhecimento
     */
    function delete_area_conhecimento($id)
    {
        return $this->db->delete('area_conhecimento',array('id'=>$id));
    }
}
