<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Atividade_extraclasse_has_aluno_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get atividade_extraclasse_has_aluno by id
     */
    function get_atividade_extraclasse_has_aluno($id)
    {
        return $this->db->get_where('atividade_extraclasse_has_aluno',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all atividade_extraclasse_has_aluno
     */
    function get_all_atividade_extraclasse_has_aluno()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('atividade_extraclasse_has_aluno')->result_array();
    }
        
    /*
     * function to add new atividade_extraclasse_has_aluno
     */
    function add_atividade_extraclasse_has_aluno($params)
    {
        $this->db->insert('atividade_extraclasse_has_aluno',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update atividade_extraclasse_has_aluno
     */
    function update_atividade_extraclasse_has_aluno($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('atividade_extraclasse_has_aluno',$params);
    }
    
    /*
     * function to delete atividade_extraclasse_has_aluno
     */
    function delete_atividade_extraclasse_has_aluno($id)
    {
        return $this->db->delete('atividade_extraclasse_has_aluno',array('id'=>$id));
    }
}
