<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Atividade_extraclasse_has_docente_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get atividade_extraclasse_has_docente by id
     */
    function get_atividade_extraclasse_has_docente($id)
    {
        return $this->db->get_where('atividade_extraclasse_has_docente',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all atividade_extraclasse_has_docente
     */
    function get_all_atividade_extraclasse_has_docente()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('atividade_extraclasse_has_docente')->result_array();
    }
        
    /*
     * function to add new atividade_extraclasse_has_docente
     */
    function add_atividade_extraclasse_has_docente($params)
    {
        $this->db->insert('atividade_extraclasse_has_docente',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update atividade_extraclasse_has_docente
     */
    function update_atividade_extraclasse_has_docente($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('atividade_extraclasse_has_docente',$params);
    }
    
    /*
     * function to delete atividade_extraclasse_has_docente
     */
    function delete_atividade_extraclasse_has_docente($id)
    {
        return $this->db->delete('atividade_extraclasse_has_docente',array('id'=>$id));
    }
}
