<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Atividade_extraclasse_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get atividade_extraclasse by id
     */
    function get_atividade_extraclasse($id)
    {
        return $this->db->get_where('atividade_extraclasse',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all atividade_extraclasse
     */
    function get_all_atividade_extraclasse()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('atividade_extraclasse')->result_array();
    }
        
    /*
     * function to add new atividade_extraclasse
     */
    function add_atividade_extraclasse($params)
    {
        $this->db->insert('atividade_extraclasse',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update atividade_extraclasse
     */
    function update_atividade_extraclasse($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('atividade_extraclasse',$params);
    }
    
    /*
     * function to delete atividade_extraclasse
     */
    function delete_atividade_extraclasse($id)
    {
        return $this->db->delete('atividade_extraclasse',array('id'=>$id));
    }
}
