<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cidade_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cidade by id
     */
    function get_cidade($id)
    {
        return $this->db->get_where('cidade',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all cidade
     */
    function get_all_cidade()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('cidade')->result_array();
    }
        
    /*
     * function to add new cidade
     */
    function add_cidade($params)
    {
        $this->db->insert('cidade',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cidade
     */
    function update_cidade($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('cidade',$params);
    }
    
    /*
     * function to delete cidade
     */
    function delete_cidade($id)
    {
        return $this->db->delete('cidade',array('id'=>$id));
    }
}
