<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cor_raca_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cor_raca by id
     */
    function get_cor_raca($id)
    {
        return $this->db->get_where('cor_raca',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all cor_raca
     */
    function get_all_cor_raca()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('cor_raca')->result_array();
    }
        
    /*
     * function to add new cor_raca
     */
    function add_cor_raca($params)
    {
        $this->db->insert('cor_raca',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cor_raca
     */
    function update_cor_raca($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('cor_raca',$params);
    }
    
    /*
     * function to delete cor_raca
     */
    function delete_cor_raca($id)
    {
        return $this->db->delete('cor_raca',array('id'=>$id));
    }
}
