<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Docente_has_disciplina_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get docente_has_disciplina by id
     */
    function get_docente_has_disciplina($id)
    {
        return $this->db->get_where('docente_has_disciplina',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all docente_has_disciplina
     */
    function get_all_docente_has_disciplina()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('docente_has_disciplina')->result_array();
    }
        
    /*
     * function to add new docente_has_disciplina
     */
    function add_docente_has_disciplina($params)
    {
        $this->db->insert('docente_has_disciplina',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update docente_has_disciplina
     */
    function update_docente_has_disciplina($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('docente_has_disciplina',$params);
    }
    
    /*
     * function to delete docente_has_disciplina
     */
    function delete_docente_has_disciplina($id)
    {
        return $this->db->delete('docente_has_disciplina',array('id'=>$id));
    }
}
