<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Escola_origem_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get escola_origem by id
     */
    function get_escola_origem($id)
    {
        return $this->db->get_where('escola_origem',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all escola_origem
     */
    function get_all_escola_origem()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('escola_origem')->result_array();
    }
        
    /*
     * function to add new escola_origem
     */
    function add_escola_origem($params)
    {
        $this->db->insert('escola_origem',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update escola_origem
     */
    function update_escola_origem($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('escola_origem',$params);
    }
    
    /*
     * function to delete escola_origem
     */
    function delete_escola_origem($id)
    {
        return $this->db->delete('escola_origem',array('id'=>$id));
    }
}
