<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Faixa_renda_pc_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get faixa_renda_pc by id
     */
    function get_faixa_renda_pc($id)
    {
        return $this->db->get_where('faixa_renda_pc',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all faixa_renda_pc
     */
    function get_all_faixa_renda_pc()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('faixa_renda_pc')->result_array();
    }
        
    /*
     * function to add new faixa_renda_pc
     */
    function add_faixa_renda_pc($params)
    {
        $this->db->insert('faixa_renda_pc',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update faixa_renda_pc
     */
    function update_faixa_renda_pc($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('faixa_renda_pc',$params);
    }
    
    /*
     * function to delete faixa_renda_pc
     */
    function delete_faixa_renda_pc($id)
    {
        return $this->db->delete('faixa_renda_pc',array('id'=>$id));
    }
}
