<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Situacao_matricula_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get situacao_matricula by id
     */
    function get_situacao_matricula($id)
    {
        return $this->db->get_where('situacao_matricula',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all situacao_matricula
     */
    function get_all_situacao_matricula()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('situacao_matricula')->result_array();
    }
        
    /*
     * function to add new situacao_matricula
     */
    function add_situacao_matricula($params)
    {
        $this->db->insert('situacao_matricula',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update situacao_matricula
     */
    function update_situacao_matricula($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('situacao_matricula',$params);
    }
    
    /*
     * function to delete situacao_matricula
     */
    function delete_situacao_matricula($id)
    {
        return $this->db->delete('situacao_matricula',array('id'=>$id));
    }
}
