<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_cotum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipo_cotum by id
     */
    function get_tipo_cotum($id)
    {
        return $this->db->get_where('tipo_cota',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tipo_cota
     */
    function get_all_tipo_cota()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tipo_cota')->result_array();
    }
        
    /*
     * function to add new tipo_cotum
     */
    function add_tipo_cotum($params)
    {
        $this->db->insert('tipo_cota',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_cotum
     */
    function update_tipo_cotum($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tipo_cota',$params);
    }
    
    /*
     * function to delete tipo_cotum
     */
    function delete_tipo_cotum($id)
    {
        return $this->db->delete('tipo_cota',array('id'=>$id));
    }
}
